### ISSUE TITLE
你好：指纹验证成功onAuthenticationSucceeded后，对result.getCryptoObject().getCipher().doFinal()有疑问

### ISSUE THREAD

**Issue by AndreTsao** [feelschaotic/FingerPrintAuth#2]
doFinal方法会检查结果是不是会拦截或者篡改过，如果是的话会抛出一个异常，异常的时候都将认证当做是失败来处理。请问这个说法是真的吗？哪里可以找到文档，谢谢。

**Comment by feelschaotic** [comment]
Cipher类是Java加密库类，具体可以看官方文档，希望可以解答你的疑惑：

- [指纹识别谷歌文档](https://developer.android.google.cn/reference/android/hardware/fingerprint/FingerprintManager.html)
- [Cipher类文档](https://developer.android.google.cn/reference/javax/crypto/Cipher)
